# Generated by Django 4.1.5 on 2023-01-24 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, help_text='Введите имя материала для печати', max_length=100, null=True, verbose_name='Материал для печати')),
                ('price', models.FloatField(help_text='Стоимость печати в руб.', max_length=100, verbose_name='За 1 метр квадратный')),
                ('resolution_print', models.IntegerField(blank=True, default=None, help_text='разрешение для печати на материале', null=True, verbose_name='DPI')),
            ],
        ),
        migrations.CreateModel(
            name='UploadArhive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_file', models.FileField(upload_to='image/arhive/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя файла')),
                ('quantity', models.IntegerField(default=1, help_text='Введите количество', verbose_name='Количество')),
                ('width', models.FloatField(default=0, help_text='Указывается в см.', verbose_name='Ширина')),
                ('length', models.FloatField(default=0, help_text='Указывается в см.', verbose_name='Длина')),
                ('resolution', models.IntegerField(default=0, help_text='для баннера 72 dpi, для Пленки 150 dpi', verbose_name='Разрешение')),
                ('color_model', models.CharField(choices=[('RGB', 'rgb'), ('CMYK', 'cmyk'), ('GREY', 'Greyscale'), ('LAB', 'lab')], help_text='Для корректной печати модель должна быть CMYK', max_length=10, verbose_name='Цветовая модель')),
                ('size', models.FloatField(default=0, verbose_name='Размер в Мб')),
                ('path_file', models.FileField(upload_to='image/%y_%m_%d')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'единица заказа',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ul', models.CharField(help_text='Форма собственности и название', max_length=70, verbose_name='Имя юр. лица')),
                ('adress_ur', models.TextField(blank=True, help_text='Полный почтовый адрес', null=True, verbose_name='Юр. Адрес')),
                ('adress_post', models.TextField(blank=True, null=True, verbose_name='Почтовый Адрес')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('e_mail', models.EmailField(blank=True, max_length=20, verbose_name='Электронная почта')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, max_length=12, verbose_name='ОКПО')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name_ul'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dostavka', models.CharField(max_length=100, verbose_name='Способ доставки')),
                ('status', models.CharField(max_length=100, verbose_name='Статус заказа')),
                ('zametki', models.TextField(max_length=500, verbose_name='Для заметок')),
                ('summa_order', models.FloatField(verbose_name='Сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.organisation', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
